flowchart TD

subgraph GitHub - neurospin-deepinsight.github.io/nidl
nidl_doc_dev["<code>/dev"]
nidl_doc_stable["<code>/stable"]
end

subgraph GitHub - nidl
DocumentationBuilder["documentation.yml"]
artifacts@{ shape: docs, label: "doc build artifacts" }
end

DocumentationBuilder -- on main --> nidl_doc_dev
DocumentationBuilder -- on GitHub release ---> nidl_doc_stable
DocumentationBuilder -- on PR --> artifacts

