accelerator: auto
accumulate_grad_batches: 1
barebones: false
benchmark: null
callbacks:
- !!python/object:nidl.callbacks.regression_metrics.RegressionMetricsCallback
  _cache: []
  prog_bar: true
  when: on_validation_epoch_end
check_val_every_n_epoch: 1
default_root_dir: null
detect_anomaly: false
deterministic: null
devices: auto
enable_checkpointing: false
enable_model_summary: null
enable_progress_bar: null
encoder: mlp
encoder_kwargs:
  layers:
  - 284
  - 128
  - 128
  n_embedding: 1
fast_dev_run: false
gradient_clip_algorithm: null
gradient_clip_val: null
inference_mode: true
learning_rate: 0.001
limit_predict_batches: null
limit_test_batches: null
limit_train_batches: null
limit_val_batches: null
log_every_n_steps: null
logger: !!python/object:pytorch_lightning.loggers.csv_logs.CSVLogger
  _experiment: null
  _flush_logs_every_n_steps: 100
  _fs: !!python/object/apply:fsspec.spec.make_instance
  - !!python/name:fsspec.implementations.local.LocalFileSystem ''
  - !!python/tuple []
  - {}
  _name: lightning_logs
  _prefix: ''
  _root_dir: .
  _save_dir: .
  _version: null
loss: l1
lr_scheduler: constant
lr_scheduler_kwargs: null
max_epochs: 3
max_steps: -1
max_time: null
min_epochs: null
min_steps: null
num_nodes: 1
num_sanity_val_steps: null
optimizer: sgd
optimizer_kwargs:
  momentum: 0.9
  weight_decay: 0.0001
overfit_batches: 0.0
plugins: null
precision: null
profiler: null
reload_dataloaders_every_n_epochs: 0
strategy: auto
sync_batchnorm: false
use_distributed_sampler: true
val_check_interval: null
